SET IDENTITY_INSERT [dbo].[Mesure] ON
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (1, N'Mesure sur les données', N'Chiffrement', N'Moyens mis en œuvre pour assurer la confidentialité des données conservées (en base de données, dans des fichiers plats, dans les sauvegardes, etc.) ainsi que les modalités de gestion des clés de chiffrement (création, conservation, modification en cas de suspections de compromission, etc.). 

Détaillez les moyens de chiffrement employés pour les flux de données (VPN, TLS, etc.) intégrés dans le traitement.', N'Décrivez ici les moyens cryptographiques mis en oeuvre pour assurer la confidentialité et l''intégrité des données.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (2, N'Mesure sur les données', N'Anonymisation', N'Description des mécanismes d’anonymisation, des garanties qu''ils apportent contre une réidentification éventuelle et à quelle fin ils sont mis en oeuvre.', N'Décrivez ici les mécanismes d''anonymisation mis en oeuvre.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (3, N'Mesure sur les données', N'Cloisonnement', N'Méthodes utilisées pour cloisonner le traitement.', N'Indiquez ici si un cloisonnement du traitement est prévu, et comment il est réalisé.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (4, N'Mesure sur les données', N'Contrôle des accès logiques', N'Description de la manière dont les profils utilisateurs sont définis et attribués. Il conviendra de détailler les moyens d’authentification mis en œuvre en précisant, le cas échéant précisez les règles applicables aux mots de passe (longueur minimale, structure obligatoire, durée de validité, nombre de tentatives infructueuses avant blocage du compte, etc.).', N'Indiquez ici comment les profils utilisateurs sont définis et attribués.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (5, N'Mesure sur les données', N'Journalisation', N'Politiques de journalisation des événements et de conservation des traces qui en résultent.', N'Indiquez ici si des évènements sont journalisés et la durée de conservation de ces traces.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (6, N'Mesure sur les données', N'Archivage', N'Politique de conservation et gestion d’archives électroniques contenant des données à caractère personnel destinées à garantir leur valeur, notamment juridique, pendant toute la durée nécessaire (versement, stockage, migration, accessibilité, élimination, politique d''archivage, protection de la confidentialité, etc.).', N'Indiquez ici l''ensemble des modalités de conservation et gestion d''archives électroniques contenant des données à caractère personnel.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (7, N'Mesure sur les données', N'Sécurisation des documents papier', N'Politiques concernant les documents papiers contenant des données sont utilisés dans le cadre du traitement. Elles décrivent comment ils sont imprimés, stockés, détruits et échangés.', N'Indiquez ici les procédures concernant le cycle de vie des documents papier contenant des données à caractère personnel.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (8, N'Mesure sur les données', N'Minimisation des données', N'La sensibilité des données peut être réduite à l''aide des méthodes suivantes : filtrage et retrait, réduction de la sensibilité par transformation, réduction du caractère identifiant des données, réduction de l''accumulation de données, restriction de l’accès aux données', N'Décrivez ici les méthodes mises en oeuvre pour réduire la sensibilité des données.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (9, N'Mesure générale de sécurité du système', N'Sécurisation de l''exploitation', N'Politiques permettant de limiter la vraisemblance et la gravité des risques visant les biens supports utilisés en exploitation (documenter les procédures d''exploitation, inventaire et mise à jour des logiciels et matériels, correction des vulnérabilités, duplication des données, limiter l''accès physique au matériel, etc.).', N'Décrivez ici les moyens mis en oeuvre pour garantir la mise à jour et le niveau de sécurité des logiciels utilisés.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (10, N'Mesure générale de sécurité du système', N'Lutte contre les logiciels malveillants', N'Mesures destinées à protéger les accès vers des réseaux publics (Internet) ou non maîtrisés (partenaires), ainsi que les postes de travail et les serveurs contre les codes malveillants qui pourraient affecter la sécurité les données à caractère personnel.', N'Décrivez ici les mesures de protection contre les codes malveillants lors d''accès à des réseaux d''un niveau de sécurité moindre.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (11, N'Mesure générale de sécurité du système', N'Gestion des postes de travail', N'Mesures prises afin de diminuer la possibilité que les caractéristiques des logiciels (systèmes d’exploitation,applications métiers, logiciels bureautiques, paramétrages…) ne soient exploitées pour porter atteinte aux données à caractère personnel (mises à jour, protection physique et des accès, travail sur un espace réseau sauvegardé, contrôleurs d’intégrité, journalisation, etc.).', N'Décrivez ici les mesures prises afin de diminuer les risques d''attaques contre les logiciels exploités par le traitement.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (12, N'Mesure générale de sécurité du système', N'Protection des sites web', N'Méthodes et moyens mis en place pour diminuer la possibilité que les caractéristiques des sites web soient exploitées pour porter atteinte aux données à caractère personnel (référentiel général de sécurité, chiffrement TLS des flux, politique de dépôt de cookies, audits de sécurité, etc.).', N'Décrivez ici les méthodes et moyens mis en oeuvre pour protéger les sites web.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (13, N'Mesure générale de sécurité du système', N'Sauvegarde des données', N'Existence d''une politique de sauvegarde permettant d''assurer la disponibilité et/ou l’intégrité des données à caractère personnel, tout en protégeant leur confidentialité (régularité des sauvegardes, chiffrement du canal de transmission des données, test d''intégrité, etc.).', N'Indiquez ici comment les sauvegardes sont gérées et conservées.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (14, N'Mesure générale de sécurité du système', N'Maintenance', N'Existence d''une politique de maintenance physique des équipements, précisant le recours éventuel à la sous-traitance.
Elle devra encadrer la maintenance à distance si elle est autorisée, et préciser les méthodes de gestion des matériels défectueux.', N'Décrivez ici comment est gérée la maintenance physique des équipements.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (15, N'Mesure générale de sécurité du système', N'Contrat de sous-traitance', N'Les données à caractère personnel communiquées à ou gérées par des sous-traitants doivent bénéficier de garanties suffisantes. Faire appel uniquement à des sous-traitants présentant des garanties suffisantes (notamment en termes de connaissances spécialisées, de fiabilité et de ressources). Exiger la communication par le prestataire de sa politique de sécurité des systèmes d’information. 
Prendre et documenter les moyens (audits de sécurité, visite des installations, etc.) permettant d’assurer l’effectivité des garanties offertes par le sous-traitant en matière de protection des données. Ces garanties incluent notamment :
- le chiffrement des données selon leur sensibilité ou à défaut l’existence de procédures garantissant que la société de prestation n’a pas accès aux données qui lui sont confiées
- le chiffrement des transmissions de données (ex : connexion de type HTTPS, VPN, etc.)
- des garanties en matière de protection du réseau, de traçabilité (journaux, audits), de gestion des habilitations, d’authentification, etc.
Prévoir un contrat avec les sous-traitants, qui définit notamment l’objet, la durée, la finalité du traitement et les obligations des parties. S’assurer qu’il contient en particulier des dispositions fixant :
- leur obligation en matière de confidentialité des données personnelles confiées
- des contraintes minimales en matière d’authentification des utilisateurs
- les conditions de restitution et/ou de destruction des données en fin du contrat
- les règles de gestion et de notification des incidents. Celles-ci devraient comprendre une information du responsable de traitement en cas de découverte de faille de sécurité ou d’incident de sécurité et cela dans les plus brefs délais lorsqu’il s’agit d’une violation de données à caractère personnel.
- Dans le cas de l’utilisation de fournisseur de cloud computing :
1. identifier clairement les données et les traitements qui passeront dans le cloud ;
2. définir ses propres exigences de sécurité technique et juridique ;
3. conduire une étude de risques afin d''identifier les mesures de sécurité appropriées ;
4. identifier le type de cloud pertinent pour le traitement envisagé ;
5. choisir un prestataire présentant des garanties suffisantes ;
6. revoir la politique de sécurité interne ;
7. surveiller les évolutions dans le temps.', N'Décrivez ici les garanties contractuelles assurant la protection des données à caractère personnel confiées à des sous traitant.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (16, N'Mesure générale de sécurité du système', N'Sécurisation des canaux informatiques', N'En fonction du type de réseau sur lequel le traitement est mis en œuvre (isolé, privé, ou Internet), le responsable de traitement doit mettre en place des systèmes de protection adéquats : pare-feu, sondes de détection d''intrusion ou autres dispositifs actifs ou passifs sont chargés d''assurer la sécurité du réseau.', N'Indiquez ici sur quel type de réseau le traitement est mis en oeuvre et les équipements assurant sa sécurisation.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (17, N'Mesure générale de sécurité du système', N'Sécurité physique', N'Existence d''un contrôle des accès physique aux locaux hébergeant le traitement (zonage, accompagnement des visiteurs, port de badge, portes verrouillées, etc.).
Indiquez s’il existe des moyens d’alerte en cas d’effraction.
', N'Indiquez ici la manière dont est réalisée le contrôle d''accès physique aux locaux hébergeant le traitement.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (18, N'Mesure générale de sécurité du système', N'Traçabilité', N'Existence de mesures mises en place pour être capable de détecter les incidents concernant des données à caractère personnel de façon précoce et de disposer d’éléments exploitables pour les étudier ou pour fournir des preuves dans le cadre d’enquêtes (architecture et politique de journalisation, respect des obligation en matière de protection des données à caractère personnel, etc.).', N'Décrivez ici les mesures mises en place pour être capable de détecter les incidents concernant des données à caractère personnel.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (19, N'Mesure générale de sécurité du système', N'Sécurisation des matériels', N'Existence de mesures prises pour diminuer la possibilité que les caractéristiques des matériels (serveurs, postes fixes, ordinateurs portables, périphériques, relais de communication, supports amovibles, etc.) soient exploitées pour porter atteinte aux données à caractère personnel (inventaire, cloisonnement, redondance matérielle, limiter l''accès, etc.).', N'Décrivez ici les méthodes et moyens mis en place pour limiter les risques d''attaques contre le matériel utilisé par le traitement.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (20, N'Mesure générale de sécurité du système', N'Eloignement des sources de risques', N'Existence de mesures pour éviter que des sources de risques, humaines ou non humaines, auxquelles il est possible de ne pas être confronté, portent atteinte aux données à caractère personnel (produits dangereux, zones géographiques dangereuses, transfert des données en dehors de l''UE, etc.).', N'Décrivez ici les méthodes et moyens mis en place pour éviter les risques qui peuvent l''être.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (30, N'Mesure générale de sécurité du système', N'Protection contre les sources de risques non humaines', N'Existence de mesures pour réduire ou éviter les risques liés à des sources non humaines (phénomènes climatiques, incendie, dégât des eaux, accidents internes ou externes, animaux, etc.) qui pourraient affecter la sécurité des données à caractère personnel (mesures de prévention, détection, protection, etc.).', N'Décrivez ici les mesures prises pour réduire ou éviter les risques liés à des sources non humaines.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (31, N'Mesure organisationnelle', N'Organisation de la politique de protection de la vie privée', N'Existence d’une organisation apte à diriger et contrôler la protection des données à caractère personnel au sein de l’organisme (désignation d''un un CIL/DPD, création d''un comité de suivi, etc.).', N'Décrivez ici l''organisation de la protection de la vie privée au sein de votre organisme.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (32, N'Mesure organisationnelle', N'Gérer la politique de protection de la vie privée', N'Le Responsable de traitement doit disposer d’une base documentaire formalisant les objectifs et les règles à appliquer dans le domaine « Informatique et libertés » (plan d''action, révision régulière de la politique « Informatique et libertés », etc.).', N'Décrivez ici les méthodes de gestion de la base documentaire encadrant l''organisation de la protection de la vie privée au sein de votre organisme.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (33, N'Mesure organisationnelle', N'Gérer les risques', N'Existence d''une politique définissant les processus destinés à maîtriser les risques que les traitements de l’organisme font peser sur les droits et libertés des personnes concernées (recensement des traitements de données à caractère personnel, des données, des supports, appréciation des risques, déterminer les mesures existantes ou prévues, etc.).', N'Décrivez ici les processus destinés à maîtriser les risques que les traitements de l''organisme font peser sur les droits et libertés des personnes concernées. ')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (34, N'Mesure organisationnelle', N'Intégrer la protection de la vie privée dans les projets', N'Existence de procédures décrivant les méthodes destinées à prendre en compte la protection des données à caractère personnel dans tout nouveau traitement (labels de confiance, référentiels, gestion des risques pour la personne concernée selon la méthodologie CNIL ou une méthode interne, etc.).', N'Décrivez ici les méthodes assurant la prise en compte de la protection des données à caractère personnel dès l''initiation d''un nouveau projet.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (35, N'Mesure organisationnelle', N'Gérer les incidents de sécurité et les violations de données', N'Existence d’une organisation opérationnelle permettant de détecter et de traiter les événements susceptibles d’affecter les libertés et la vie privée des personnes concernées (définition des responsabilités, plan de réaction, qualifier les violations, etc.).', N'Décrivez ici les processus opérationnels destinés à détecter et traiter les évènements susceptibles d''affecter la vie privée des personnes concernées.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (36, N'Mesure organisationnelle', N'Gestion des personnels', N'Existence d''un plan encadrant les mesures de sensibilisation prises à l’arrivée d’une personne dans sa fonction et d''une procédure décrivant les mesures prises au départ des personnes accédant aux données.', N'Indiquez ici les mesures de votre politique de ressource humaine répondant aux problématiques informatique et libertés dans votre organisme.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (37, N'Mesure organisationnelle', N'Superviser la protection de la vie privée', N'Existence de mesures permettant de disposer d’une vision globale et à jour de l’état de protection des données et de la conformité au RGPD (contrôler la conformité des traitements, objectifs et indicateurs, responsabilités, etc.).', N'Décrivez ici les processus qui assurent un contrôle régulier des traitments de données.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (38, N'Mesure organisationnelle', N'Gestion des tiers accédant aux données.', N'Existence d''une procédure visant à réduire les risques que les accès légitimes aux données par des tiers peuvent faire peser sur les libertés et la vie privée des personnes concernées (identification des tiers, contrat de sous-traitance, convention, BCR, etc.).', N'Indiquez ici, pour les tiers amenés à avoir accès aux données, les modalités et les mesures de sécurités mises en oeuvre pour ces accès.')
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (39, N'Définition', N'Chiffrement', N'Le chiffrement d’un message permet de garantir que seuls l’émetteur et le(s) destinataire(s) légitime(s) d’un message en connaissent le contenu. C’est une sorte d’enveloppe scellée numérique. Une fois chiffré, faute d''avoir la clé spécifique, un message est inaccessible et illisible, que ce soit par les humains ou les machines.
Il existe deux grandes familles de chiffrement : le chiffrement symétrique et le chiffrement asymétrique.
- Le chiffrement symétrique permet de chiffrer et de déchiffrer un contenu avec la même clé, appelée alors la « clé secrète ». Le chiffrement symétrique est particulièrement rapide mais nécessite que l’émetteur et le destinataire se mettent d’accord sur une clé secrète commune ou se la transmettent par un autre canal. Celui-ci doit être choisi avec précautions, sans quoi la clé pourrait être récupérée par les mauvaises personnes, ce qui n’assurerait plus la confidentialité du message.
- Le chiffrement asymétrique suppose que le (futur) destinataire est muni d’une paire de clés (clé privée, clé publique) et qu’il a fait en sorte que les émetteurs potentiels aient accès à sa clé publique. Dans ce cas, l’émetteur utilise la clé publique du destinataire pour chiffrer le message tandis que le destinataire utilise sa clé privée pour le déchiffrer. Parmi ses avantages, la clé publique peut être connue de tous et publiée. Mais attention : il est nécessaire que les émetteurs aient confiance en l’origine de la clé publique, qu’ils soient sûrs qu’il s’agit bien de celle du destinataire. Autre point fort : plus besoin de partager une même clé secrète ! Le chiffrement asymétrique permet de s’en dispenser mais il est plus lent.', NULL)
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (40, N'Définition', N'Anonymisation', N'Le but d''une solution d''anonymisation est de faire perdre le caractère identifiant des données à caractère personnel. Une solution d’anonymisation doit être construite au cas par cas et adaptée aux usages prévus. Pour aider à évaluer une bonne solution d’anonymisation, le G29 propose trois critères :
- L’individualisation : est-il toujours possible d’isoler un individu ?
- La corrélation : est-il possible de relier entre eux des ensembles de données distincts concernant un même individu ?
- L’inférence : peut-on déduire de l’information sur un individu ? 
Ainsi : un ensemble de données pour lequel il n’est possible ni d’individualiser ni de corréler ni d’inférer est a priori anonyme ;
un ensemble de données pour lequel au moins un des trois critères n’est pas respecté ne pourra être considéré comme anonyme qu’à la suite d’une analyse détaillée des risques de ré-identification.', NULL)
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (41, N'Définition', N'Pseudonymisation', N'Traitement des données à caractère personnel de telle façon que celles-ci ne puissent plus être attribuées à une personne concernée précise sans avoir recours à des informations supplémentaires, pour autant que ces informations supplémentaires soient conservées séparément et soumises à des mesures techniques et organisationnelles afin de garantir que les données à caractère personnel ne sont pas attribuées à une personne physique identifiée ou identifiable.
La pseudonymisation réduit le risque de mise en corrélation d’un ensemble de données avec l’identité originale d’une personne concernée; à ce titre, c’est une mesure de sécurité utile, mais non une méthode d''anonymisation.', NULL)
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (42, N'Définition', N'Cloisonnement', N'Ensemble de méthodes permettant de réduire la possibilité de corréler des données à caractère personnel et de provoquer une violation de l’ensemble des données .
On pourra par exemple identifier les données propres à chaque métier, les séparer logiquement, etc.', NULL)
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (43, N'Définition', N'Contrôle d''accès logique', N'Il consiste à limiter les risques que des personnes non autorisées accèdent aux données à caractère personnel sous forme numérique.
Pour cela, il convient de :
- définir des profils d’habilitation dans les systèmes en séparant les tâches et les domaines de responsabilité, afin de limiter l’accès des utilisateurs aux seules données strictement nécessaires à l’accomplissement de leurs missions. 
- supprimer les permissions d’accès des utilisateurs dès qu’ils ne sont plus habilités à accéder à un local ou à une ressource informatique, ainsi qu’la fin de leur contrat. 
- Réaliser une revue annuelle des habilitations afin d’identifier et de supprimer les comptes non utilisés et de réaligner les droits accordés sur les fonctions de chaque utilisateur.', NULL)
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (44, N'Définition', N'Mot de passe', N'Basée sur la gestion d’un secret, l’authentification par identifiant et mot de passe est un moyen simple et peu coûteux à déployer pour contrôler un accès. Toutefois, cette méthode d’authentification présente un niveau de sécurité faible.
Les exigences minimales de la CNIL en termes de taille et de complexité du mot de passe varient en fonction des mesures complémentaires mises en place pour fiabiliser le processus d’authentification :
ainsi, si une authentification est basée exclusivement sur un mot de passe, cela implique a minima l’utilisation d’un mot de passe complexe d’au moins 12 caractères composé de majuscules de minuscules, de chiffres et de
caractères spéciaux. Des mesures complémentaires à la saisie d’un mot de passe (restrictions, d’accès, collecte d’autres donnée, support détenu en propre par l’utilisateur) permettent de réduire la longueur et la complexité du mot de passe, car ces mesures permettent d’assurer un niveau de sécurité équivalent au mot de passe seul.', NULL)
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (45, N'Définition', N'Authentification', N'L''authentification est une opération par laquelle l''utilisateur apporte la preuve de son identité, pour cela il existe plusieurs mécanismes catégorisés selon qu’ils font intervenir :
- ce que l’on sait, par exemple un mot de passe ;
- ce que l’on a, par exemple une carte à puce ;
- une caractéristique qui nous est propre, par exemple une empreinte digitale ou encore la manière de rédiger une signature manuscrite.
Pour rappel, la loi Informatique et Libertés subordonne l’utilisation de la biométrie à l’autorisation préalable de la CNIL
L’authentification d’un utilisateur est qualifiée de forte lorsqu’elle a recours à une combinaison d’au moins deux de ces catégories.', NULL)
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (46, N'Définition', N'Journalisation', N'Dispositif permettant d’enregistrer des actions effectuées sur le système informatique afin de pouvoir identifier un accès frauduleux ou une utilisation abusive de données personnelles, ou de déterminer l’origine d’un incident. Il convient d’enregistrer certaines des actions effectuées sur les systèmes informatiques. Pour ce faire, un dispositif de gestion des traces et des incidents doit être mis en place. Celui-ci doit enregistrer les évènements pertinents et garantir que ces enregistrements ne peuvent être altérés. Dans tous les cas, il ne faut pas conserver ces éléments pendant une durée excessive.', NULL)
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (47, N'Définition', N'Archivage', N'Les données qui ne sont plus utilisées au quotidien mais qui n’ont pas encore atteint leur durée limite de conservation, par exemple parce qu’elles sont conservées en cas de contentieux, devraient être archivées.

Les archives doivent être sécurisées notamment si les données archivées sont des données sensibles, ou des données qui pourraient avoir des impacts graves sur les personnes concernées.', NULL)
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (48, N'Définition', N'Filtrage et retrait', N'Lors de l''importation de données, différents types de métadonnées (par exemple, des données EXIF attachées avec un fichier d''image) peuvent être involontairement collectés.
Ces métadonnées doivent être identifiées et éliminées si elles ne sont pas nécessaires aux finalités spécifiées.', NULL)
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (49, N'Définition', N'Réduction de la sensibilité par transformations', N'Après réception de données sensibles, faisant partie d’un lot d’informations générales ou transmises à des fins statistiques uniquement, celles-ci peuvent être converties en une forme moins sensible ou pseudonymisée. Par exemple :
- si le système collecte l’adresse IP pour déterminer l''emplacement de l’utilisateur dans un but statistique, l’adresse IP peut être supprimées après déduction de la ville ou du quartier ;
- si le système reçoit des données vidéo à partir de caméras de surveillance, il peut reconnaître les personnes debout ou en mouvement dans la scène et les flouter ;
- si le système est un compteur intelligent, il peut agréger l''utilisation de l''énergie sur une certaine période, sans l’enregistrer en temps réel.', NULL)
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (50, N'Définition', N'Gestion de projet', N'Démarche consistant à prendre en compte la protection des données à caractère personnel dans tout nouveau traitement (labels de confiance, référentiels, gestion des risques pour la personne concernée selon la méthodologie de la CNIL ou une méthode interne, etc.), notamment :
- Utiliser la démarche de gestion des risques de la CNIL dès l’élaboration d’un service ou la conception d’une application.
- Privilégier le recours à des labels de confiance dans les domaines de la SSI et « Informatique et libertés » (procédures, produits, systèmes de management, organismes, personnes, etc.).
- Privilégier le recours à des référentiels éprouvés et reconnus.', NULL)
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (51, N'Définition', N'Violation de données', N'Violation de la sécurité entraînant, de manière accidentelle ou illicite, la destruction, la perte, l''altération, la divulgation non autorisée de données à caractère personnel transmises, conservées ou traitées d''une autre manière, ou l''accès non autorisé à de telles données.', NULL)
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (52, N'Définition', N'Réduction du caractère identifiant des données', N'Le système peut faire en sorte que :
- l’utilisateur peut utiliser une ressource ou un service sans risque de divulguer son identité (données anonymes) ;
- l’utilisateur peut utiliser une ressource ou un service sans divulguer son identité, mais reste identifiable et responsable de cette utilisation (données pseudonymes) ;
- l’utilisateur peut faire de multiples utilisations des ressources ou des services sans risque que ces utilisations puissent être reliées ensemble (données non corrélables) ;
- l’utilisateur peut utiliser une ressource ou un service sans risque que d’autres, en particulier des tiers, puissent être en mesure d''observer que la ressource ou le service est utilisé (non-observabilité).
Le choix d''une méthode de la liste ci-dessus doit dépendre des menaces identifiées. Pour certains types de menaces sur la vie privée, la pseudonymisation sera plus appropriée que l''anonymisation (par exemple, s''il y a un besoin de traçabilité). En outre, certaines menaces sur la vie privée seront traitées par une combinaison de plusieurs méthodes.', NULL)
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (53, N'Définition', N'Réduction de l''accumulation de données', N'Le système peut être structuré en parties indépendantes avec des fonctions de contrôle d''accès distinctes. Les données peuvent également être réparties entre ces sous-systèmes indépendants et contrôlées par chaque sous-système en utilisant différents mécanismes de contrôle d''accès. Si un sous-système est compromis, les impacts sur l’ensemble des données peuvent ainsi être réduits.', NULL)
INSERT INTO [dbo].[Mesure] ([Id], [Type], [Titre], [Description], [Tooltip]) VALUES (54, N'Définition', N'Restriction de l’accès aux données', N'Le système peut limiter l''accès aux données selon le principe du « besoin d’en connaître ». Le système peut séparer les données sensibles et appliquer des politiques de contrôle d''accès spécifiques.
Le système peut aussi chiffrer les données sensibles pour protéger leur confidentialité lors de la transmission et du stockage. L’accès aux fichiers cachés temporaires qui sont produits au cours du traitement des données devrait également être protégé.', NULL)
SET IDENTITY_INSERT [dbo].[Mesure] OFF
