INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 1, N'Nom', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 2, N'Prénom', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 3, N'Âge', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 4, N'Date de naissance', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 5, N'Lieu de naissance', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 6, N'Ancienne adresse', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 7, N'Adresse actuelle', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 8, N'Situation familiale', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 9, N'États civils', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 10, N'Numéro de registre national', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 11, N'Numéro de carte d''identité', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 12, N'Passeport', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 13, N'Amendes', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 14, N'Numéro de téléphone privé', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 15, N'Numéro de téléphone professionnel', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 16, N'Permis de conduire', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 17, N'Plaque d''immatriculation', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 18, N'Appréciation de la solvabilité ', N'Statut financier')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 19, N'Dépenses', N' Loyer, prêts, hypothèques, ...')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 20, N'Revenus', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 21, N'Biens immobiliers', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 22, N'Numéro de carte de crédits', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 23, N'Numéro de carte de débits', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 24, N'Numéro de compte bancaire', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 25, N'Parcours scolaire', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 26, N'Diplôme(s)', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 27, N'Recrutement', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 28, N'Profession', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 29, N'Pension', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 30, N'Adresse IP', N'Numéro d''identification qui est attribué de façon permanente ou provisoire à chaque branchement à un réseau informatique utilisant l''Internet Protocol')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 31, N'Historique de connexion', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 32, N'Identifiant de connexion', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 33, N'Mot de passe', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCP', 0, N'Données à caractère personnel', N'Concerne toute information relative à une personne physique identifiée ou qui peut être identifiée, directement ou indirectement, par référence à un numéro d''identification ou à plusieurs éléments qui lui sont propres')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCS', 0, N'Données à caractère sensible', N'Ensemble d''informations (relative à l''origine ethnique, la santé, opinions politique, données biométrique) pouvant mener à un type de discrimination')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCS', 1, N'Données physiques', N'Taille, poids, couleurs des cheveux et/ou yeux, signe distinctif)')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCS', 2, N'Données ADN', N'Cartographie de la séquence ADN')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCS', 3, N'Données génétiques', N'Cartographie du génome, etc ...')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCS', 4, N'Emprunte digitale', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCS', 5, N'Données médicales', N'Dossier médicale, invalidité, etc ...')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'VRB', 0, N'Vraisemblance', N'La vraisemblance traduit la possibilité qu’un risque se réalise. Elle dépend essentiellement des vulnérabilités des supports face aux menaces et des capacités des sources de risques à les exploiter.')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCS', 6, N'Composition de ménage', N'Concerne une personne vivant habituellement seule ou par 2 ou plusieurs personnes qui, unies ou non par des liens de parenté, occupent habituellement un même logement et y vivent en commun')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCS', 7, N'Origine ethnique', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCS', 8, N'Identité du genre', N'Homme, femme, transidentité')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCS', 9, N'Conviction philosophique/religieuse', N'Reflexion abstraite et rationnelle ayant pour objet la connaissance de l''être')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCS', 10, N'Affiliations politiques', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCS', 11, N'Affiliations syndicales', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCS', 12, N'Données judiciaire', N'Condamnation, casier judiciaire ')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'DCS', 13, N'Images/ vidéo de surveillance', N'Caméra dans les rues')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDM', 0, N'Sources des menaces', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'BDL', 0, N'Base de légitimation', N'Manière dont les données du traitement ont été obtenues')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'BDL', 1, N'Consentement', N'Donné par la personne concernée (oral ou écrit)')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'BDL', 2, N'Éxecution d''un contrat', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'BDL', 3, N'Obligation légale', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'BDL', 4, N'Intérêt vitale', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'BDL', 5, N'Mission d''intérêt public', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDD', 0, N'Support des données', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDD', 1, N'Systèmes informatiques', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDD', 2, N'Serveurs', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDD', 3, N'Logiciels', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDD', 4, N'Réseaux', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDD', 5, N'Personnes', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDD', 6, N'Support papier', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 0, N'Finalité des données', N'Determine à quelle fin utiles les données du traitement sont-elle utilisées.')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 1, N'Recrutement du personnel', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 2, N'Administration des salaires', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 3, N'Gestion du personnel', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 4, N'Contrôle sur le lieu de travail', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 5, N'Gestion des commandes', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 6, N'Gestion du contentieux', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 7, N'Évènements culturels', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 8, N'Sécurité', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 9, N'Impôts (taxes, redevances, ...)', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 10, N'Recouvrement de créance', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 11, N'Subventions', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 12, N'Permis', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 13, N'Tenue des registres', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 14, N'Élections', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 15, N'Administration des étrangers', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 16, N'Cadastre', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 17, N'Casier judiciaire', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 18, N'Défense judiciaire', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 19, N'Administration des élèves ', N'Organisation de l''enseignement, examens, résultats scolaires, diplômes, délibération jury, gestion des repas scolaires')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 20, N'Gestion des inscriptions', N'paiement minerval, bourse, ...')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 21, N'Gestion des membres de bibliothèques', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 22, N'Statistiques', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 23, N'Archives', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 24, N'Recensement de population', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 25, N'Registre national', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 26, N'Enquêtes publiques', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 27, N'Facturation', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'FDD', 28, N'Perception des amendes', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDM', 1, N'Administrateur informatique', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDM', 2, N'Utilisateur', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDM', 3, N'Attaque externe', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDM', 4, N'Concurrent', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDM', 5, N'Eau', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDM', 6, N'Feux', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDM', 7, N'Matériaux dangereux', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDM', 8, N'Virus informatique', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'VRB', 1, N'Vraisemblance négligeable', N'Il ne semble pas possible que les sources de risques retenues puissent réaliser la menace en s’appuyant sur les caractéristiques des supports (ex. : vol de supports papiers stockés dans un local de l’organisme dont l’accès est contrôlé par badge et code d’accès).')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'VRB', 2, N'Vraisemblance limitée', N'Il semble difficile pour les sources de risques retenues de réaliser la menace en s’appuyant sur les caractéristiques des supports (ex. : vol de supports papiers stockés dans un local de l’organisme dont l’accès est contrôlé par badge).')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'VRB', 3, N'Vraisemblance importante', N'il semble possible pour les sources de risques retenues de réaliser la menace en s’appuyant sur les caractéristiques des supports (ex. : vol de supports papiers stockés dans les bureaux d’un organisme dont l’accès est contrôlé par une personne à l’accueil).')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'VRB', 4, N'Vraisemblance maximale', N'il semble extrêmement facile pour les sources de risques retenues de réaliser la menace en s’appuyant sur les caractéristiques des supports (ex. : vol de supports papier stockés dans le hall public de l’organisme).')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'GRV', 0, N'Gravité', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'GRV', 1, N'Impact négligeable', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'GRV', 2, N'Impact limité', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'GRV', 3, N'Impact important', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'GRV', 4, N'Impact maximal', NULL)
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDR', 0, N'Source de risque', N'Personne, interne ou externe à l''organisme, agissant de manière accidentelle ou délibérée (ex : administrateur informatique, utilisateur, attaquant externe, concurrent), ou source non humaine (ex : eau, matériaux dangereux, virus informatique non ciblé) qui peut être à l’origine d’un risque.')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDR', 1, N'Source humaine interne', N'Il peut s''agir :
- d''un employé, malintentionné, utilisant sa proximité du système, ses compétences, ses privilèges et un temps disponible potentiellement élevés ou commettant une négligence due à un possible manque de formation et de sensibilisation.
- d''un utilisateur ou de son entourage, négligent ou malintentionné, ayant accès au service.
Ses motivations peuvent être multiples : maladresse, erreur, négligence, vengeance, volonté d’alerter, malveillance, appât du gain, espionnage')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDR', 2, N'Source humaine externe', N'Il peut s''agir :
- d''un tiers malintentionné ou ignorant utilisant sa proximité physique pour accéder frauduleusement au service
- d''un attaquant ciblant un utilisateur en utilisant sa connaissance de l’utilisateur et de certaines des informations le concernant
- d''un attaquant ciblant une des sociétés en charge du traitement utilisant sa connaissance des sociétés pouvant permettre d’attenter à leur image
- d''un organisme tiers autorisé utilisant ses accès privilégiés pour accéder illégitimement à des informations. Les motivations peuvent être multiples : jeu, nuisance, malveillance, vengeance, espionnage, appât du gain, acquisition de données en vue de les exploiter')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'SDR', 3, N'Source non humaine', N'Il peut s''agir d''un incident ou sinistre chez un des organismes en charge du traitement (coupure de courant, incendie, inondation, etc.)')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'PCO', 0, N'Personne concernée', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'PCO', 1, N'Citoyen', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'PCO', 2, N'Interne', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'COO', 0, N'Coordonnées', N'')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'COO', 1, N'Collège', N'Rue Saint-Martin, 52 - 7500 Tournai Tel :069/332211')
INSERT INTO [dbo].[Glossaire] ([Appl], [Code], [Libelle], [Tooltip]) VALUES (N'COO', 2, N'DPO', N'Lesplingard Anaïs  Email : anais.lesplingard@tournai.be Tel : 069/332416 GSM : 0475/725071')
